#!/bin/bash

if [ $# -eq 0 ] 
then
	echo "Usage: phone searchfor [...searchfor]"
	echo "(You didn't tell me what you want to search for.)" 
	exit 1
else

	cp mydata.txt tmp

	for arg in "$@" 
	do
		egrep -i "$arg" tmp > temp
		#cat temp
		mv temp tmp
	
	done
	awk -f display.awk tmp
fi
